### PR TITLE
stub for configurable stack vs cabal switching

### PR DESCRIPTION
**Pull request by cartazio**
I'm not sure whats a suitable way to test this more than "i think it works for me", and even that caveat aside, i'm not sure if my change touches the right points in the code base at allllll. so some feedback on that before I even mess around with testing things fully /  correctly would be appreciated

### CODE REVIEW

**Comment by cartazio** [comment]
huh, seems like the travis integration is a bit ... weak

**Comment by cartazio** [comment]
this is related to https://github.com/SublimeHaskell/SublimeHaskell/issues/246
 could @nh2  or @mvoidex  or someone give me feedback? this isn't what i'm currently using locally, i'm rather just patching the "isStack" predicate to always return false, because simpler to do when sublime packages auto update :)

**Comment by mvoidex** [comment]
Hi, sorry for delay, i'll take a look this weekend

**Comment by cartazio** [comment]
thanks! :)

**Comment by mvoidex** [comment]
Thanks, my implementation is based on yours

**Pull request closed without merging**
