### PR TITLE
stub of how to do new-build support

### PR DESCRIPTION
**Pull request by cartazio**

### CODE REVIEW

**Comment by cartazio** [comment]
The main goal here is to show how i keep on patching my local sublime every update :)

**Comment by cartazio** [comment]
@bscottm hope this is helpful :)

**Comment by bscottm** [comment]
@cartazio: Yes, it is. I'll end up changing the build selector to "cabal-new-build" so that existing "cabal" builder users don't get hosed in the transition.

**Comment by cartazio** [comment]
Yeah.  Sounds like a decent balance for medium term to support the handfuls
of power users ;)

**Comment by cartazio** [comment]
this would also let me have some projects locally have sublime settings to use cabal build (aka sandbox) when it makes sense to and otherwise default to new build?

(i'm using the mafia tool by ambiata sometimes for complicated projects https://github.com/ambiata/mafia and it does a clever version of cabal sandboxes)

**Comment by bscottm** [comment]
Manually merged into 1.2.2.

**Pull request closed without merging**
