### PR TITLE
hsdev-0.3.2.0, SublimeHaskell 2.2.0

### PR DESCRIPTION
**Pull request by mvoidex**
Major update of `hsdev`, see also #386

### CODE REVIEW

**Comment by martinstuecklschwaiger** [comment]
Any update on this?

**Comment by mvoidex** [comment]
No, I think I'll just merge it next week.

**Comment by mvoidex** [comment]
There's known bug in GHC-8.6 (https://ghc.haskell.org/trac/ghc/ticket/16071), causing ghc to freeze installing `traverse-with-class`, so I can't test new version on Windows. I'll wait until its fixed.

**Comment by Vlix** [comment]
> There's known bug in GHC-8.6 (https://ghc.haskell.org/trac/ghc/ticket/16071), causing ghc to freeze installing `traverse-with-class`, so I can't test new version on Windows. I'll wait until its fixed.

Ugh, why is GHC so broken when it comes to functionalities used by IDEs...

**Comment by mvoidex** [comment]
Created new PR: #438

**Pull request closed without merging**
