### PR TITLE
Bump hsdev required version

### LINKED ISSUE #329: Default installed version of hsdev is unsupported
I got this error after I installed SublimeHaskell:

SublimeHaskell: hsdev version is incorrect: 0.2.3.1
Required version: >= 0.2.0.0 and < 0.2.3.0
Update it by running 'cabal update' and 'cabal install hsdev'

To supress this message and disable hsdev set 'enable_hsdev' to false

### PR DESCRIPTION
**Pull request by xeoneux**
Fix #329

### CODE REVIEW

**Comment by Centril** [comment]
It might be a good idea to not have a max version at all, or at least a way to override the requirement of a max version... This way, this will become less of a permanent issue.

**Comment by bscottm** [comment]
@xeoneux: That is certainly the first step in bumping the version number. The second step is to update the options to hsdev >= 0.2.3.1.

@Centril: You still want to have a maximum version number to test what is supported vs. what is still in alpha or beta or simply escaped by accident and shouldn't be used. And for things like command line arguments changing.

**Comment by xeoneux** [comment]
@bscottm where do we update that? 😸

**Comment by bscottm** [comment]
@xeoneux: I'd have to look over at the `hsdev` issues list for the specifics of how the command line options have changed (IIRC, "--log-config" became "--config", among other things.) The code to for setting up the command line is in `hsdev/agent.py`. Then, be sure that you also update the default plugin settings in `Settings/Default.sublime-settings`, if they need to be changed.

OTOH, I am working on it, albeit not as quickly as you probably would like.

**Comment by xeoneux** [comment]
Hey @bscottm any update on this? 😸

**Comment by bscottm** [comment]
@xeoneux: Just got back from business travel and catching up. High on my free time priority list (top of my priority list is Elvis, my Labradoodle, of course.)

**Pull request closed without merging**
