### PR TITLE
hsdev-0.3.0.0

### PR DESCRIPTION
**Pull request by mvoidex**
@bscottm, created PR just to mention about huge updates in hsdev.

In this PR i've updated backend to use new API and to test hsdev-0.3.0.0

1. now uses [haskell-names](https://github.com/haskell-suite/haskell-names) to resolve names in sources, and thus `go to definition` works for local bindings
2. now stores data in sqlite, so in my case user-db + package-db + project takes ~30Mb
3. hsdev doesn't drop ghc session anymore, so consecutive checks of same module (or modules within same project) are much faster
4. added new commands:
 - `usages` - get all uses of symbol (also, as long as all data is in sql, you can easily inspect it, for example i made query to find symbols, that are used least (2 - 1 for declaration and 1 for export list), and so removed many unused stuff :)
 - `whoat` - same as `whois`, but accepts location instead of name
 - `rename` - generates same output as `autofixes` (was `autofix show`), so can be applied with `refactor` command or by editor itself

### CODE REVIEW

**Comment by bscottm** [comment]
@mvoidex: Probably want to resolve the conflicts before merging.

Q: Is hsdev-0.3.0.0 backwardly compatible? Or will everyone have to upgrade to 0.3.0.0 when they take this update? I'd suggest remaining backwardly compatible for a while, if possible.

**Comment by mvoidex** [comment]
@bscottm, hsdev-0.3.0.0 is not backward caompatible as there are many internal and some API changes.
However, I think, it's possible to support both versions, but this will require some additional work.

**Comment by mvoidex** [comment]
Why not use continuations?
Pause is definitely not short, at least in my case it takes several seconds first time and about 700-800 msecs on each consecutive check.

> Also, avoid local functions within functions.
Ok

**Comment by bscottm** [comment]
I don't disagree with continuations, on principle. In the case of check/lint, I'm trying to remember the exact reason -- I was probably trying to track down one of @Pastafarianist's "prettify_on_save doesn't work" bugs. There are a sequence of actions that depend on check/lint success before they execute, which means adding more continuations onto the check/lint code. Just easier and slightly more maintainable to make check/lint blocking.

**Comment by bscottm** [comment]
2.1.18 will make check/lint async again. <groan>

**Comment by bscottm** [comment]
@mvoidex: When did you anticipate being done on this branch? I have a little work to do on `build.py` to separate the UI code from the builder so that indent-on-save also works for that code path. Sooner or later, Pastafarianist will notice and submit an issue. ;-)

My one concern: SubHask users use this package in some pretty unusual ways, and there are also a fair number of "novices". Considering that few people restart ST3 after an upgrade, even though I've put a pretty big note at the front of the release nodes, I wonder how backwardly compatible `hsdev-0.2.x.y` will be if users don't upgrade `hsdev` to 0.3.0.0 after the update.

I think you'd be somewhat surprised by the number of users who use the `None` backend.

**Comment by mvoidex** [comment]
@bscottm, it depends on backward compatibility support
we can merge and break `hsdev-0.2.*` (response symbols/modules objects changed, so most commands won't parse result)
or I can try to support both

**Comment by bscottm** [comment]
@mvoidex: "Hindsight is 20/20" (it's easy to see good decisions or better approaches when you examine history.) It'd probably have been a better idea to take an incremental approach to adding features to `hsdev 0.3.00`. But, what is done is done.

I do wish there was some way to reach out to the entire user group to warn them about this upcoming "breaking upgrade". Unfortunately, there's no other way other than the release notes. But, once this code is released, you'll need to be available to handle the issues.

We should plan to bump the major version number to `3`, since it is a major version change.

Also, I should audit some of the commits. `fly_check` was one where I saw a few issues.

**Comment by mvoidex** [comment]
- Showing usages count in popup
- Selecting symbol usages in current file from popup (link `N in this file`)
- Output symbol usages in project from popup (link `Usages`)
- Added `Expression type` command to get type of expression (in context of current view)
- Fixed `Autofix` command
- Updated `Add import` command
- Added `lint_opts` setting to pass options to hlint
- Autocompletion: show names with qualifiers
- Added inspection of modified view (without check & lint) to resolve names and imports; settings `inspect_modified`/`inspect_modified_idle`; disabled by default

**Comment by moodmosaic** [comment]
With the latest commits that are merged from master into this branch (hsdev-3), hdocs aren't working, unless I go manually and revert 54259e5.

**Comment by moodmosaic** [comment]
In general, it'd be nice is SublimeHaskell 3.* could fix those pesky console errors:

*When opening any `.hs` file*:

```
Traceback (most recent call last):
  File "C:\Users\Nikos\Downloads\XCOPY\Sublime Text\sublime_plugin.py", line 389, in run_callback
    expr()
  File "C:\Users\Nikos\Downloads\XCOPY\Sublime Text\sublime_plugin.py", line 428, in <lambda>
    run_callback('on_load', callback, lambda: callback.on_load(v))
  File "C:\Users\Nikos\Downloads\XCOPY\Sublime Text\Data\Packages\SublimeHaskell\zzplugin.py", line 167, in on_load
    self.do_load(view)
  File "C:\Users\Nikos\Downloads\XCOPY\Sublime Text\Data\Packages\SublimeHaskell\zzplugin.py", line 199, in do_load
    if (Settings.PLUGIN.use_improved_syntax and (name.endswith(".hs") or name.endswith(".hsc"))) or \
NameError: global name 'name' is not defined
```

*When hovering the mouse over a type or expression which fires hdocs*:

```
<hsdev stderr> [96m2018-02-22 12:47:36 +0200[m[m [m[91mERROR[m[m [m[95m[m[m:[m[92mupdate/cabal/task/package-db-stack[m[m> [m[mScope leaves with exception: tool 'C:\Users\Nikos\AppData\Local\Programs\stack\x86_64-windows\ghc-8.2.2\bin\ghc-pkg.exe' failed: empty output, expecting path to user package db
<hsdev stderr> CallStack (from HasCallStack):
<hsdev stderr>   onError, called at src\System\Log\Simple\Monad.hs:104:36 in simple-log-0.9.3-AwZTZEnHmtHLEWAKWQWBHK:System.Log.Simple.Monad
<hsdev stderr> [m[m
<hsdev stderr> [96m2018-02-22 12:47:36 +0200[m[m [m[91mERROR[m[m [m[95m[m[m:[m[92mupdate/cabal/task[m[m> [m[mScope leaves with exception: tool 'C:\Users\Nikos\AppData\Local\Programs\stack\x86_64-windows\ghc-8.2.2\bin\ghc-pkg.exe' failed: empty output, expecting path to user package db
<hsdev stderr> CallStack (from HasCallStack):
<hsdev stderr>   onError, called at src\System\Log\Simple\Monad.hs:104:36 in simple-log-0.9.3-AwZTZEnHmtHLEWAKWQWBHK:System.Log.Simple.Monad
<hsdev stderr> [m[m
<hsdev stderr> [96m2018-02-22 12:47:36 +0200[m[m [m[91mERROR[m[m [m[95m[m[m:[m[92mupdate/cabal[m[m> [m[mScope leaves with exception: tool 'C:\Users\Nikos\AppData\Local\Programs\stack\x86_64-windows\ghc-8.2.2\bin\ghc-pkg.exe' failed: empty output, expecting path to user package db
<hsdev stderr> CallStack (from HasCallStack):
<hsdev stderr>   onError, called at src\System\Log\Simple\Monad.hs:104:36 in simple-log-0.9.3-AwZTZEnHmtHLEWAKWQWBHK:System.Log.Simple.Monad
<hsdev stderr> [m[m
<hsdev stderr> [96m2018-02-22 12:47:36 +0200[m[m [m[91mERROR[m[m [m[95m[m[m:[m[92mupdate[m[m> [m[mtool 'C:\Users\Nikos\AppData\Local\Programs\stack\x86_64-windows\ghc-8.2.2\bin\ghc-pkg.exe' failed: empty output, expecting path to user package db[m[m
font face "Times" could not be found, defaulting to "Consolas"
```

Other than those errors in console, I'm extremely happy with hsdev 3.* and the hsdev-3 branch of SH. 🚀

**Comment by moodmosaic** [comment]
Is there a way to somehow hide those errors from the console? (Even if I have to temporarily comment-out a few lines of code from my local SH source.)

```
<hsdev stderr> [96m2018-03-23 13:54:39 +0200[m[m	[m[91mERROR[m[m	[m[95m[m[m:[m[92mupdate/cabal/task/package-db-stack[m[m> [m[mScope leaves with exception: tool 'C:\Users\Nikos\AppData\Local\Programs\stack\x86_64-windows\ghc-8.2.2\bin\ghc-pkg.exe' failed: empty output, expecting path to user package db
<hsdev stderr> CallStack (from HasCallStack):
<hsdev stderr>   onError, called at src\System\Log\Simple\Monad.hs:104:36 in simple-log-0.9.3-AwZTZEnHmtHLEWAKWQWBHK:System.Log.Simple.Monad
<hsdev stderr> [m[m
<hsdev stderr> [96m2018-03-23 13:54:39 +0200[m[m	[m[91mERROR[m[m	[m[95m[m[m:[m[92mupdate/cabal/task[m[m> [m[mScope leaves with exception: tool 'C:\Users\Nikos\AppData\Local\Programs\stack\x86_64-windows\ghc-8.2.2\bin\ghc-pkg.exe' failed: empty output, expecting path to user package db
<hsdev stderr> CallStack (from HasCallStack):
<hsdev stderr>   onError, called at src\System\Log\Simple\Monad.hs:104:36 in simple-log-0.9.3-AwZTZEnHmtHLEWAKWQWBHK:System.Log.Simple.Monad
<hsdev stderr> [m[m
<hsdev stderr> [96m2018-03-23 13:54:39 +0200[m[m	[m[91mERROR[m[m	[m[95m[m[m:[m[92mupdate/cabal[m[m> [m[mScope leaves with exception: tool 'C:\Users\Nikos\AppData\Local\Programs\stack\x86_64-windows\ghc-8.2.2\bin\ghc-pkg.exe' failed: empty output, expecting path to user package db
<hsdev stderr> CallStack (from HasCallStack):
<hsdev stderr>   onError, called at src\System\Log\Simple\Monad.hs:104:36 in simple-log-0.9.3-AwZTZEnHmtHLEWAKWQWBHK:System.Log.Simple.Monad
<hsdev stderr> [m[m
<hsdev stderr> [96m2018-03-23 13:54:39 +0200[m[m	[m[91mERROR[m[m	[m[95m[m[m:[m[92mupdate[m[m> [m[mtool 'C:\Users\Nikos\AppData\Local\Programs\stack\x86_64-windows\ghc-8.2.2\bin\ghc-pkg.exe' failed: empty output, expecting path to user package db[m[m
```

**Comment by mvoidex** [comment]
@moodmosaic there's issue https://github.com/mvoidex/hsdev/issues/81, i'll try to fix it this weekend

**Comment by moodmosaic** [comment]
Sounds great <3 In general is there a way to disable *all* output from hsdev in SH so that it doesn't show up in the ST3 console?

**Comment by moodmosaic** [comment]
(Even if it can be done by modifying something in the source code, I'm fine doing that in my local SH source.)

**Comment by mvoidex** [comment]
Uploaded [hsdev-0.3.1.3](https://hackage.haskell.org/package/hsdev-0.3.1.3) with flag `--no-color` to disable colorized output

**Comment by moodmosaic** [comment]
Anyone seen this?

>With the latest commits that are merged from master into this branch (hsdev-3), hdocs aren't working, unless I go manually and revert 54259e5.

Is this still the case? I'm a bit scared to just pull the latest.

**Comment by moodmosaic** [comment]
OK, I pulled the latest from `hsdev-3` and everything seems to work fine regarding https://github.com/SublimeHaskell/SublimeHaskell/pull/386#issuecomment-375849532.

**Comment by mvoidex** [comment]
@bscottm do you have any suggestions, what should be done here before merge?
Right now I have no plans to modify `hsdev`, so it's somehow stable now.
I'm using this branch and it seems to work for me.

It's not backward compatible now. I understand that it's not good to force users to use new hsdev version, but I'm not sure if I can find enough time to support both versions.

**Comment by moodmosaic** [comment]
Works fine for me too. It's fine to force users to upgrade to the same major version of hsdev, according to https://semver.org.

Perhaps, it's also a good chance to mention SemVer 2.0 on the README as well, if you guys follow it.

**Comment by moodmosaic** [comment]
Even better, then.

**Comment by juanmbellini** [comment]
Any news about this?

**Comment by mvoidex** [comment]
@juanmbellini I was out of process for a long time and not sure if we can safely merge it

I've updated `hsdev` and going to upload new version compatible with current stackage LTS
There's also [hsdev-0.3.2.0](https://github.com/SublimeHaskell/SublimeHaskell/tree/hsdev-0.3.2.0) branch for new hsdev version.

Check & lint works for me, but there's something wrong with autocompletion. `hsdev` returns correct completions, but SublimeHaskell doesn't show them. I'll try to fix it as soon as possible and update branch.

**Comment by mvoidex** [comment]
Completions fixed: https://github.com/SublimeHaskell/SublimeHaskell/commit/de5610faf2ef1ed83abe8b935d48abd9e2e706c7

**Comment by mvoidex** [comment]
Closing in favor of #429

**Pull request closed without merging**
