### PR TITLE
Fix crashing backend and freezing issues

### LINKED ISSUE #371: Sublime freezes
So when opening sublime it tries to load SublimeHaskell. However it freezes on the build.
When closing and reopening Sublime it gives the following error messages:

```
No usable backends (hsdev, ghc-mod) found on PATH or in the standard Haskell cabal and stack installation locations. 
Please check or update your SublimeHaskell user settings, or install hsdev or ghc-mod.
```

However other times it will build and work perfectly.  I'm running cabal 1.24.0.2 and hsdev 0.2.5.1. I also checked and cabal is added to the PATH. 
Can you help me fix this?

### PR DESCRIPTION
**Pull request by ROpdebee**
Fixes #371 

Putting back the `wait_complete` keyword in `autofix_show` seems to fix the freezing issues. At least it does for me.

### CODE REVIEW

**Comment by bscottm** [comment]
My bad. I thought I had reverted this change in the release. Will merge and update.

**Comment by bscottm** [comment]
@ROpdebee: Are you sure you restarted SH after the update installed? I just did another similar change, ended up with a traceback because there were still outstanding references to an older Python module. Reloading the plugin/restarting ST fixed the issue.

**Comment by ROpdebee** [comment]
Which update are we talking about? Package Control hasn't updated SH to 2.1.4 yet, and I've restarted ST/reloaded SH numerous times before and after I've made the changes in this PR locally.

I'll check out 2.1.4 soon and I'll let you know what I find.

**Comment by ROpdebee** [comment]
Updating SH to 2.1.4 (I had to manually instruct Package Control to do so) worked fine after a restart. I had to restart because it got confused and said it couldn't find any backend, but it does that sometimes and quitting Sublime fixes that. Other than that, no issues/freezing/tracebacks whatsoever it seems.

**Comment by bscottm** [comment]
@ROpdebee: Yes, that will happen due to how modules load in Python, with stale references to existing modules persisting until you restart. There's no "sure fire" way to update a ST package and ensure that the previous package is completely unloaded. SH has a few internal libraries, which aren't unloaded or unreferenced when a package update occurs.

Also, if you change SH code locally, bear in mind that Package Control pulls the package directly from github. So you have uncommitted changes that Package Control won't overwrite unless you give it permission to do so.

Bascially, I think I need to remind users to RESTART YOUR SUBLIMETEXT AFTER AN UPDATE. :-)

**Pull request merged**
